In [13]:
import torch

t = torch.rand(10)
print(t)
torch.sort(t)
print(t)

tensor([0.7309, 0.7713, 0.6955, 0.5359, 0.0893, 0.0735, 0.2703, 0.8467, 0.2813,
        0.7980])
tensor([0.7309, 0.7713, 0.6955, 0.5359, 0.0893, 0.0735, 0.2703, 0.8467, 0.2813,
        0.7980])


In [17]:
values, ind = torch.sort(t)

In [21]:
values

tensor([0.0735, 0.0893, 0.2703, 0.2813, 0.5359, 0.6955, 0.7309, 0.7713, 0.7980,
        0.8467])

In [27]:
torch.sqrt(torch.tensor(2500))

tensor(50.)